llm:
  provider : "google"
  chat_model : "gemini-2.0-flash-lite"

embedding_model:
  provider : "google"
  model_name : "models/text-embedding-004"

retriever:
  top_k : 2

astra_db:
  collection_name : "finance_v2"
